### ISSUE TITLE
Add Linux distro dependency information

### ISSUE THREAD

**Issue by lberrymage** [lberrymage/accrescent#26]
Add per-distro package dependency list to README. Should at least include the following distros (in alphabetical order):

- Arch Linux

- Debian/Ubuntu

- Fedora

- openSUSE

Most of this info should be found in the [Amethyst README](https://github.com/amethyst/amethyst/blob/master/README.md).

Make sure to include a one-line command to install the dependencies for each distro, not a bulletpoint list.

**Comment by aayux** [comment]
I understand that (at least at this time) the package list would be exactly the same as in the Amethyst README, except that it does not have instructions for CentOS and Gentoo. Should I just go ahead and add what we have?

As a side note: I'm new to Rust and am looking to contribute more to this project, however at this point it's not very clear to me as to where this is going -- but I will keep track of it and hopefully I'll be able to commit some actual code soon.

**Comment by lberrymage** [comment]
That's correct; the package list should be almost the same (I didn't include NixOS because it has a comparatively smaller user base, I'm not familiar with its package management system, and I like to understand what I commit :grin: . If someone requests it, we can add it then).

Now that I look into it more, I don't think we need instructions for CentOS or Gentoo at all, at least for the time being. Since Gentoo is minimalist like Arch Linux, the packages required should be the same (with potentially different naming). CentOS uses the same package format as Fedora and should have the exact same installation command save for the replacing `dnf` with `yum`. So yes, just add what we have. I'll reflect this in the top comment.

I'm glad to hear that! A more in-depth explanation of the project should come once I decide the specifics on structure, API, and the like. A rough idea of what I want to create is something similar to [Minetest](https://www.minetest.net/), but with a focus on a native API through dynamic loading in addition to a Lua API. There should also be a strong focus on having a very playable "main" game.

Let me know if you have any questions. I know that was wordy.
